name: update-dependencies-action-no-gh
on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:     
  update-dep:
    runs-on: ubuntu-latest
    steps:          
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - uses: actions/checkout@v3
        with:
          ref: update-dependencies

      - name: git fetch and reset master 
        run: |
          git fetch origin master
          git reset --hard origin/master
      
      - name: Perform dependency resolution and write new lockfiles
        run: ./gradlew dependencies --write-locks

      - name: Commit and push
        run: |
          if ! git diff --quiet HEAD; then
            git config --global user.name 'Github Action Bot'
            git config --global user.email 'jakub.wieczorek0101@gmail.com'
            git add .
            git commit -m "build(gradle): Update gradle.lockfile"
            git push --force origin update-dependencies
          else 
            echo no dynamic dependencies updates
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create pull request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: 'build(gradle): Update dependencies',
              owner,
              repo,
              head: '${{ github.ref_name }}',
              base: 'master',
              body: [
                'Auto-generated dependency update'
              ].join('\n')
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['tutorials', 'patch-version']
            });
