name: update-dependencies-action
on:
  schedule:
    - cron:  '*/5 * * * *'
  workflow_dispatch:

jobs:     
  update-dep:
    runs-on: ubuntu-latest
    steps:          
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - uses: actions/checkout@v3
        with:
          ref: update-dependencies

      - name: git fetch and rebase 
        run: |
          git fetch origin master
          git rebase origin/master
      
      - name: Perform dependency resolution and write new lockfiles
        run: ./gradlew dependencies --write-locks

      - name: Commit and push
        run: |
          git config --global user.name 'Github Action Bot'
          git config --global user.email 'jakub.wieczorek0101@gmail.com'
          git add .
          git commit -m "gradle.lockfile update"
          git push --force origin update-dependencies
        
      - name: Create Pull Request
        run: gh pr create -B master -H update-dependencies --title 'Update dependencies' --body 'Auto-generated dependency update'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}